services:
  # 1. Le Front-end Angular (servi par Nginx)
  front:
    build: 
      context: ./FRONT/front
    ports:
      - "4200:80"
    networks:
      - web-ia-network

  # 2. Le relais Java / Spring Boot
  spring:
    build: 
      context: ./BackSpring/backspring
    ports:
      - "8080:8080"
    networks:
      - web-ia-network

  # 3. Le relais Python / Django
  django:
    build: 
      context: ./BackDjango/backdjango
    ports:
      - "8000:8000"
    networks:
      - web-ia-network

# On crée un réseau virtuel privé pour que nos conteneurs puissent
# communiquer entre eux si besoin (même si le Front passe par le navigateur).
networks:
  web-ia-network:
    driver: bridge