services:
  # 1. Le Front-end Angular
  angular:
    build: 
      context: ./FRONT/front
    ports:
      - "4200:80"

  # 2. Le Front-end React
  react:
    build: 
      context: ./FRONTREACT/front-react
    ports:
      - "5173:80"

  # 3. Le relais Java / Spring Boot
  spring:
    build: 
      context: ./BackSpring/backspring
    ports:
      - "8080:8080"
    environment:
      # Injecte le chemin pour le conteneur Docker
      - DB_PATH=/app/database/iabdd
    volumes:
      # Persistance des données Spring
      - ./spring_data:/app/database

  # 4. Le relais Python / Django
  django:
    build: 
      context: ./BackDjango/backdjango
    ports:
      - "8000:8000"
    volumes:
      - ./BackDjango/backdjango:/app
    # 👉 AJOUTE CES DEUX LIGNES :
    env_file:
      - ./BackDjango/backdjango/.env
    environment:
      - PYTHONUNBUFFERED=1