server {
    listen 80;
    server_name localhost;

    # Le dossier où Nginx va chercher les fichiers compilés
    root /usr/share/nginx/html;
    index index.html;

    # Redirection magique pour les Single Page Applications
    location / {
        try_files $uri $uri/ /index.html;
    }
}