# Generated by Django 5.1.4 on 2026-06-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                (
                    "mot_de_passe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("role", models.CharField(default="ROLE_USER", max_length=20)),
                ("auth_provider", models.CharField(default="LOCAL", max_length=20)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "UTILISATEUR",
            },
        ),
        migrations.CreateModel(
            name="Visage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("chemin_image", models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
