spring.application.name=backspring
server.port=8080

# URL de l'IA
python.api.url=https://elgronaldo-web-ia.hf.space/api/chat

# --- BDD H2 FLEXIBLE (Docker ou Local) ---
# Si DB_PATH est défini par Docker, on l'utilise. Sinon, on crée un dossier /db localement
spring.datasource.url=jdbc:h2:file:${DB_PATH:./db/iabdd}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# --- IMPORT DES SECRETS (Doit exister dans src/main/resources) ---
spring.config.import=optional:classpath:application-secret.properties


# Tailles maximales pour les fichiers
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.web.error.include-message=always