spring.application.name=backspring
# Le port de ton Spring Boot
server.port=8080

# L'URL de ton API Python (Change-la par ton URL Hugging Face quand ce sera en ligne)
python.api.url=https://elgronaldo-web-ia.hf.space/api/chat

# IMPORTANT : Augmenter la taille maximale des requêtes JSON (pour laisser passer les gros fichiers Base64)
server.tomcat.max-http-form-post-size=50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.error.include-message=always